name: CI
#on: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      version:
        default: "patch"
        description: Version used to publish the new package (and how to increment package version)
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 21
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v5
        with:
          node-version: 21
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: pnpm i
      - run: pnpm release --no-publish --branch ${{ github.ref_name }} ${{ inputs.version }}
      - run: pnpm publish
