name: CI
#on: workflow_dispatch
on:
  push:
    branches:
      - feat/update-release-ci
jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 21
    steps:
      - uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version}}
          package-manager-cache: false
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version}}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: pnpm i
      - run: pnpm release --branch ${{ github.ref_name }}
